root: ./

structure:  
    readme: README.md  
    summary: SUMMARY.md

redirects:  
    getting-started-with-crowd-dev-api: ./README.md
    activities-api: ./README.md
    post_tenant-tenantid-activity-with-member: ./README.md
    post_tenant-tenantid-activity: ./README.md
    delete_tenant-tenantid-activity-id: ./README.md
    get_tenant-tenantid-activity-id: ./README.md
    put_tenant-tenantid-activity-id: ./README.md
    post_tenant-tenantid-activity-query: ./README.md
    post_tenant-tenantid-settings-activity-types: ./README.md
    get_tenant-tenantid-settings-activity-types: ./README.md
    put_tenant-tenantid-settings-activity-types-key: ./README.md
    post_tenant-tenantid-automation: ./README.md
    get_tenant-tenantid-automation: ./README.md
    delete_tenant-tenantid-automation-automationid: ./README.md
    get_tenant-tenantid-automation-automationid: ./README.md
    put_tenant-tenantid-automation-automationid: ./README.md
    get_tenant-tenantid-automation-automationid-executions: ./README.md
    conversations-api: ./README.md
    post_tenant-tenantid-conversation: ./README.md
    get_tenant-tenantid-conversation: ./README.md
    delete_tenant-tenantid-conversation-id: ./README.md
    get_tenant-tenantid-conversation-id: ./README.md
    put_tenant-tenantid-conversation-id: ./README.md
    members-api: ./README.md
    get_tenant-tenantid-member-active: ./README.md
    post_tenant-tenantid-member: ./README.md
    delete_tenant-tenantid-member-id: ./README.md
    get_tenant-tenantid-member-id: ./README.md
    put_tenant-tenantid-member-id: ./README.md
    post_tenant-tenantid-member-export: ./README.md
    post_tenant-tenantid-member-query: ./README.md
    post_tenant-tenantid-settings-members-attributes: ./README.md
    delete_tenant-tenantid-settings-members-attributes: ./README.md
    get_tenant-tenantid-settings-members-attributes: ./README.md
    get_tenant-tenantid-settings-members-attributes-id: ./README.md
    put_tenant-tenantid-settings-members-attributes-id: ./README.md
    put_tenant-tenantid-enrichment-member-id: ./README.md
    post_tenant-tenantid-note: ./README.md
    delete_tenant-tenantid-note-id: ./README.md
    get_tenant-tenantid-note-id: ./README.md
    put_tenant-tenantid-note-id: ./README.md
    post_tenant-tenantid-note-query: ./README.md
    organizations: ./README.md
    post_tenant-tenantid-organization: ./README.md
    delete_tenant-tenantid-organization-id: ./README.md
    get_tenant-tenantid-organization-id: ./README.md
    put_tenant-tenantid-organization-id: ./README.md
    post_tenant-tenantid-organization-query: ./README.md
    tags-api: ./README.md
    post_tenant-tenantid-tag: ./README.md
    get_tenant-tenantid-tag: ./README.md
    delete_tenant-tenantid-tag-id: ./README.md
    get_tenant-tenantid-tag-id: ./README.md
    put_tenant-tenantid-tag-id: ./README.md
    post_tenant-tenantid-task-batch: ./README.md
    post_tenant-tenantid-task: ./README.md
    delete_tenant-tenantid-task-id: ./README.md
    get_tenant-tenantid-task-id: ./README.md
    put_tenant-tenantid-task-id: ./README.md
    post_tenant-tenantid-task-query: ./README.md
    sending-data-from-integrations: ./README.md
    sending-data-from-github: ./README.md
    sending-data-from-discord: ./README.md
    sending-data-from-slack: ./README.md
    sending-data-from-twitter: ./README.md
    query-operators: ./README.md
    members-query: ./README.md
    query-activities: ./README.md
    query-organizations: ./README.md
    query-conversations: ./README.md
    query-tags: ./README.md
