root: ./

​structure:  
    readme: README.md  
    summary: SUMMARY.md​

redirects:  
    product-docs: ./README.md
    activity-sentiment: ./guides/activities/activity-sentiment.md
    member-profiles: ./guides/contacts/contact-profiles.md
